/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.4/userguide/multi_project_builds.html
 */

rootProject.name = "mycookbook"

// application contains business logic
include(":core")

// adapters
include(":application")
include(":store")
include(":integration")

// domain contains models and their logic
include(":domain:user")
include(":domain:recipe")
include(":domain:groceries")
include(":domain:dayplan")
